// Code generated by "stringer -type=ChatMemberKind -output stringer.go -linecomment"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Creator-1]
	_ = x[Administrator-2]
	_ = x[Member-3]
	_ = x[Restricted-4]
	_ = x[Left-5]
	_ = x[Kicked-6]
}

const _ChatMemberKind_name = "creatoradministratormemberrestrictedleftkicked"

var _ChatMemberKind_index = [...]uint8{0, 7, 20, 26, 36, 40, 46}

func (i ChatMemberKind) String() string {
	i -= 1
	if i >= ChatMemberKind(len(_ChatMemberKind_index)-1) {
		return "ChatMemberKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ChatMemberKind_name[_ChatMemberKind_index[i]:_ChatMemberKind_index[i+1]]
}
